name: 'GitFlow Workflow Action'
description: 'Manages GitFlow releases and hotfixes'
author: 'Andrew Franklin Leo'

inputs:
  develop_branch:
    description: 'Name of the develop branch'
    required: true
    default: 'develop'
  main_branch:
    description: 'Name of the main branch'
    required: true
    default: 'main'
  version:
    description: 'Version to release'
    required: false
  release_summary:
    description: 'Release summary'
    required: false
    default: ''
  dry_run:
    description: 'Run in dry run mode'
    required: false
    default: 'false'

outputs:
  type:
    description: 'Type of the release (release or hotfix)'
    value: ${{ steps.prepare.outputs.type }}
  version:
    description: 'Version of the release'
    value: ${{ steps.prepare.outputs.version }}
  pull_number:
    description: 'Pull request number'
    value: ${{ steps.create_pr.outputs.pull_number }}

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Get release type and branch
      id: prepare
      shell: bash
      run: |
        # Determine if this is a release or hotfix based on branch name
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          branch="${{ github.event.pull_request.head.ref }}"
          if [[ "$branch" == release/* ]]; then
            echo "type=release" >> $GITHUB_OUTPUT
          elif [[ "$branch" == hotfix/* ]]; then
            echo "type=hotfix" >> $GITHUB_OUTPUT
          else
            echo "type=none" >> $GITHUB_OUTPUT
          fi
          echo "version=${branch#*/}" >> $GITHUB_OUTPUT
        else
          # For workflow_dispatch
          if [[ "${{ github.base_ref }}" == "${{ inputs.main_branch }}" ]]; then
            echo "type=hotfix" >> $GITHUB_OUTPUT
          else
            echo "type=release" >> $GITHUB_OUTPUT
          fi
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        fi

    - name: Create release branch
      if: inputs.dry_run != 'true'
      shell: bash
      run: |
        # Determine branch to create from
        if [[ "${{ steps.prepare.outputs.type }}" == "hotfix" ]]; then
          git checkout ${{ inputs.main_branch }}
          git pull origin ${{ inputs.main_branch }}
        else
          git checkout ${{ inputs.develop_branch }}
          git pull origin ${{ inputs.develop_branch }}
        fi
        
        branch_name="${{ steps.prepare.outputs.type }}/${{ steps.prepare.outputs.version }}"
        git checkout -b "$branch_name"
        
        # Update version in package.json
        npm version ${{ steps.prepare.outputs.version }} --no-git-tag-version
        
        git add package.json package-lock.json
        git commit -m "chore: bump version to ${{ steps.prepare.outputs.version }}"
        git push origin "$branch_name"

    - name: Create pull request
      if: inputs.dry_run != 'true'
      id: create_pr
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        branch_name="${{ steps.prepare.outputs.type }}/${{ steps.prepare.outputs.version }}"
        pr_title="${{ steps.prepare.outputs.type }}: ${{ steps.prepare.outputs.version }}"
        
        # Create PR body with template
        pr_body="## ${{ steps.prepare.outputs.type }} ${{ steps.prepare.outputs.version }}

        ${{ inputs.release_summary }}

        ## Deployment Checklist
        - [ ] All tests passing
        - [ ] Documentation updated
        - [ ] Environment variables configured
        - [ ] Database migrations verified
        - [ ] Monitoring configured
        
        ## Changes
        $(git log ${{ inputs.main_branch }}..$branch_name --format="* %s")"
        
        # Create PR
        pr_url=$(gh pr create \
          --base "${{ inputs.main_branch }}" \
          --head "$branch_name" \
          --title "$pr_title" \
          --body "$pr_body" \
          --label "automated")
        
        echo "pull_number=$(echo $pr_url | grep -o '[0-9]\+$')" >> $GITHUB_OUTPUT

    - name: Tag release
      if: |
        inputs.dry_run != 'true' && 
        github.event_name == 'pull_request' && 
        github.event.pull_request.merged == true
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git checkout ${{ inputs.main_branch }}
        git pull origin ${{ inputs.main_branch }}
        
        version="${{ steps.prepare.outputs.version }}"
        git tag -a "v${version}" -m "Release ${version}"
        git push origin "v${version}"
        
        gh release create "v${version}" \
          --title "Release ${version}" \
          --notes "${{ inputs.release_summary }}" \
          --target ${{ inputs.main_branch }}

    - name: Merge back to develop
      if: |
        inputs.dry_run != 'true' && 
        github.event_name == 'pull_request' && 
        github.event.pull_request.merged == true &&
        steps.prepare.outputs.type == 'release'
      shell: bash
      run: |
        git checkout ${{ inputs.develop_branch }}
        git pull origin ${{ inputs.develop_branch }}
        git merge --no-ff ${{ inputs.main_branch }} -m "chore: merge release ${{ steps.prepare.outputs.version }} back to develop"
        git push origin ${{ inputs.develop_branch }}